# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bp.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bp_sync(object):
    def setupUi(self, bp_sync):
        bp_sync.setObjectName("bp_sync")
        bp_sync.resize(480, 800)
        bp_sync.setStyleSheet("background-color:rgb(0, 0,128);")
        self.pname_5 = QtWidgets.QLabel(bp_sync)
        self.pname_5.setGeometry(QtCore.QRect(20, 514, 151, 43))
        self.pname_5.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pname_5.setFont(font)
        self.pname_5.setAutoFillBackground(False)
        self.pname_5.setStyleSheet("color:rgb(255,255,255);")
        self.pname_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pname_5.setObjectName("pname_5")
        self.pname_3 = QtWidgets.QLabel(bp_sync)
        self.pname_3.setGeometry(QtCore.QRect(20, 490, 151, 43))
        self.pname_3.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pname_3.setFont(font)
        self.pname_3.setAutoFillBackground(False)
        self.pname_3.setStyleSheet("color:rgb(255,255,255);")
        self.pname_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pname_3.setObjectName("pname_3")
        self.frame = QtWidgets.QFrame(bp_sync)
        self.frame.setGeometry(QtCore.QRect(9, 103, 461, 181))
        self.frame.setStyleSheet("background-color:rgb(108,130,187);\n"
"border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(165, 19, 290, 143))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pname = QtWidgets.QLabel(self.layoutWidget)
        self.pname.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pname.setFont(font)
        self.pname.setAutoFillBackground(False)
        self.pname.setStyleSheet("color:rgb(255,255,255);")
        self.pname.setObjectName("pname")
        self.verticalLayout.addWidget(self.pname)
        self.lname = QtWidgets.QLabel(self.layoutWidget)
        self.lname.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lname.setFont(font)
        self.lname.setAutoFillBackground(False)
        self.lname.setStyleSheet("color:rgb(255,255,255);")
        self.lname.setObjectName("lname")
        self.verticalLayout.addWidget(self.lname)
        self.hn = QtWidgets.QLabel(self.layoutWidget)
        self.hn.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.hn.setFont(font)
        self.hn.setAutoFillBackground(False)
        self.hn.setStyleSheet("color:rgb(255,255,255);")
        self.hn.setObjectName("hn")
        self.verticalLayout.addWidget(self.hn)
        self.pimage = QtWidgets.QLabel(self.frame)
        self.pimage.setGeometry(QtCore.QRect(8, 5, 150, 171))
        self.pimage.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pimage.setFont(font)
        self.pimage.setAutoFillBackground(False)
        self.pimage.setStyleSheet("background-color:rgb(108,130,187);\n"
"border-radius: 5px;")
        self.pimage.setText("")
        self.pimage.setPixmap(QtGui.QPixmap("./image/no_image.png"))
        self.pimage.setObjectName("pimage")
        self.label_2 = QtWidgets.QLabel(bp_sync)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 360, 40))
        self.label_2.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgb(255,0,0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(bp_sync)
        self.label_3.setGeometry(QtCore.QRect(22, 20, 71, 71))
        self.label_3.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgb(255,0,0);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./image/logo.png"))
        self.label_3.setObjectName("label_3")
        self.pname_4 = QtWidgets.QLabel(bp_sync)
        self.pname_4.setGeometry(QtCore.QRect(20, 370, 151, 43))
        self.pname_4.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pname_4.setFont(font)
        self.pname_4.setAutoFillBackground(False)
        self.pname_4.setStyleSheet("color:rgb(255,255,255);")
        self.pname_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pname_4.setObjectName("pname_4")
        self.pname_7 = QtWidgets.QLabel(bp_sync)
        self.pname_7.setGeometry(QtCore.QRect(20, 630, 151, 43))
        self.pname_7.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pname_7.setFont(font)
        self.pname_7.setAutoFillBackground(False)
        self.pname_7.setStyleSheet("color:rgb(255,255,255);")
        self.pname_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pname_7.setObjectName("pname_7")
        self.label = QtWidgets.QLabel(bp_sync)
        self.label.setGeometry(QtCore.QRect(100, 26, 301, 30))
        self.label.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgb(255,0,0);")
        self.label.setObjectName("label")
        self.pname_2 = QtWidgets.QLabel(bp_sync)
        self.pname_2.setGeometry(QtCore.QRect(20, 345, 151, 43))
        self.pname_2.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pname_2.setFont(font)
        self.pname_2.setAutoFillBackground(False)
        self.pname_2.setStyleSheet("color:rgb(255,255,255);")
        self.pname_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pname_2.setObjectName("pname_2")
        self.txt_sys = QtWidgets.QLCDNumber(bp_sync)
        self.txt_sys.setGeometry(QtCore.QRect(180, 350, 271, 131))
        self.txt_sys.setStyleSheet("background-color:rgb(192,192,192);\n"
"border-radius: 10px;")
        self.txt_sys.setDigitCount(4)
        self.txt_sys.setMode(QtWidgets.QLCDNumber.Dec)
        self.txt_sys.setProperty("value", 0.0)
        self.txt_sys.setObjectName("txt_sys")
        self.txt_pulse = QtWidgets.QLCDNumber(bp_sync)
        self.txt_pulse.setGeometry(QtCore.QRect(180, 630, 271, 131))
        self.txt_pulse.setStyleSheet("background-color:rgb(192,192,192);\n"
"border-radius: 10px;")
        self.txt_pulse.setDigitCount(4)
        self.txt_pulse.setProperty("value", 0.0)
        self.txt_pulse.setProperty("intValue", 0)
        self.txt_pulse.setObjectName("txt_pulse")
        self.pname_6 = QtWidgets.QLabel(bp_sync)
        self.pname_6.setGeometry(QtCore.QRect(20, 654, 151, 43))
        self.pname_6.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pname_6.setFont(font)
        self.pname_6.setAutoFillBackground(False)
        self.pname_6.setStyleSheet("color:rgb(255,255,255);")
        self.pname_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pname_6.setObjectName("pname_6")
        self.txt_dai = QtWidgets.QLCDNumber(bp_sync)
        self.txt_dai.setGeometry(QtCore.QRect(180, 490, 271, 131))
        self.txt_dai.setStyleSheet("background-color:rgb(192,192,192);\n"
"border-radius: 10px;")
        self.txt_dai.setDigitCount(4)
        self.txt_dai.setProperty("value", 0.0)
        self.txt_dai.setProperty("intValue", 0)
        self.txt_dai.setObjectName("txt_dai")
        self.pname_8 = QtWidgets.QLabel(bp_sync)
        self.pname_8.setGeometry(QtCore.QRect(10, 10, 461, 88))
        self.pname_8.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pname_8.setFont(font)
        self.pname_8.setAutoFillBackground(False)
        self.pname_8.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgb(255,0,0);\n"
"border-radius: 5px;")
        self.pname_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pname_8.setAlignment(QtCore.Qt.AlignCenter)
        self.pname_8.setObjectName("pname_8")
        self.txterror = QtWidgets.QLabel(bp_sync)
        self.txterror.setGeometry(QtCore.QRect(10, 290, 451, 34))
        self.txterror.setMinimumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.txterror.setFont(font)
        self.txterror.setAutoFillBackground(False)
        self.txterror.setStyleSheet("color:rgb(255,0,0);")
        self.txterror.setText("")
        self.txterror.setObjectName("txterror")
        self.pname_8.raise_()
        self.pname_6.raise_()
        self.pname_5.raise_()
        self.pname_3.raise_()
        self.frame.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pname_4.raise_()
        self.pname_7.raise_()
        self.label.raise_()
        self.pname_2.raise_()
        self.txt_sys.raise_()
        self.txt_pulse.raise_()
        self.txt_dai.raise_()
        self.txterror.raise_()

        self.retranslateUi(bp_sync)
        QtCore.QMetaObject.connectSlotsByName(bp_sync)

    def retranslateUi(self, bp_sync):
        _translate = QtCore.QCoreApplication.translate
        bp_sync.setWindowTitle(_translate("bp_sync", "Form"))
        self.pname_5.setText(_translate("bp_sync", "mmHg"))
        self.pname_3.setText(_translate("bp_sync", "DAI"))
        self.pname.setText(_translate("bp_sync", "ชื่อ :ยุทธนา"))
        self.lname.setText(_translate("bp_sync", "สกุล :ตาสุภา"))
        self.hn.setText(_translate("bp_sync", "HN :12516662"))
        self.label_2.setText(_translate("bp_sync", "ระบบบันทึกข้อมูล ความดันโลหิต อัตโนมัติ"))
        self.pname_4.setText(_translate("bp_sync", "mmHg"))
        self.pname_7.setText(_translate("bp_sync", "PULSE"))
        self.label.setText(_translate("bp_sync", "PQ-BP Sync"))
        self.pname_2.setText(_translate("bp_sync", "SYS"))
        self.pname_6.setText(_translate("bp_sync", "/min"))
        self.pname_8.setText(_translate("bp_sync", "เชื่อมต่อกับอุปกรณ์ไม่ได้"))
